import uuid
import json
import datetime
import os
import sqlite3

from flask import Flask, request, jsonify
from dotenv import load_dotenv
from groq import Groq

load_dotenv()

app = Flask(__name__)
client = Groq(api_key=os.environ.get("GROQ_API_KEY"))

# ---------------------------------------------------------------------------
# Database
# ---------------------------------------------------------------------------

def init_db():
    conn = sqlite3.connect("audit.db")
    conn.execute("""
        CREATE TABLE IF NOT EXISTS log (
            content_id  TEXT,
            creator_id  TEXT,
            timestamp   TEXT,
            attribution TEXT,
            confidence  REAL,
            llm_score   REAL,
            status      TEXT
        )
    """)
    conn.commit()
    conn.close()


def write_log(entry: dict):
    conn = sqlite3.connect("audit.db")
    conn.execute(
        "INSERT INTO log VALUES (?,?,?,?,?,?,?)",
        (
            entry["content_id"],
            entry["creator_id"],
            entry["timestamp"],
            entry["attribution"],
            entry["confidence"],
            entry["llm_score"],
            entry["status"],
        ),
    )
    conn.commit()
    conn.close()


def get_log(n: int = 20) -> list[dict]:
    conn = sqlite3.connect("audit.db")
    rows = conn.execute(
        "SELECT * FROM log ORDER BY timestamp DESC LIMIT ?", (n,)
    ).fetchall()
    conn.close()
    cols = ["content_id", "creator_id", "timestamp", "attribution",
            "confidence", "llm_score", "status"]
    return [dict(zip(cols, row)) for row in rows]


# ---------------------------------------------------------------------------
# Signal 1: LLM classification
# ---------------------------------------------------------------------------

def llm_classify(text: str) -> float:
    """
    Ask the LLM to assess whether text is AI-generated.
    Returns a float 0.0 (confident human) – 1.0 (confident AI).
    """
    prompt = (
        "Analyze the following text and assess whether it was written by a human "
        "or generated by an AI writing tool.\n\n"
        "Return ONLY a JSON object in this exact format, with no other text:\n"
        '{"ai_score": 0.0}\n\n'
        "Where ai_score is a float between 0.0 (confident the text is human-written) "
        "and 1.0 (confident the text is AI-generated).\n\n"
        f"Text to analyze:\n{text}"
    )

    response = client.chat.completions.create(
        model="llama-3.3-70b-versatile",
        messages=[{"role": "user", "content": prompt}],
        temperature=0.1,
    )

    raw = response.choices[0].message.content.strip()

    try:
        result = json.loads(raw)
        return float(result["ai_score"])
    except (json.JSONDecodeError, KeyError, ValueError) as e:
        print(f"[llm_classify] Failed to parse response: {e!r}")
        print(f"[llm_classify] Raw output was: {raw!r}")
        # Return 0.5 (maximally uncertain) so the submission doesn't hard-fail
        return 0.5


# ---------------------------------------------------------------------------
# Routes
# ---------------------------------------------------------------------------

@app.route("/submit", methods=["POST"])
def submit():
    data = request.get_json(force=True, silent=True)
    if not data:
        return jsonify({"error": "Invalid or missing JSON body"}), 400

    text = data.get("text", "").strip()
    creator_id = data.get("creator_id", "").strip()

    if not text:
        return jsonify({"error": "Missing required field: text"}), 400
    if not creator_id:
        return jsonify({"error": "Missing required field: creator_id"}), 400

    content_id = str(uuid.uuid4())
    llm_score = llm_classify(text)

    # Placeholder attribution based on llm_score alone (M4 adds the weighted score)
    if llm_score >= 0.65:
        attribution = "likely_ai"
    elif llm_score >= 0.36:
        attribution = "uncertain"
    else:
        attribution = "likely_human"

    entry = {
        "content_id": content_id,
        "creator_id": creator_id,
        "timestamp": datetime.datetime.utcnow().isoformat() + "Z",
        "attribution": attribution,
        "confidence": llm_score,   # placeholder — M4 replaces with weighted score
        "llm_score": llm_score,
        "status": "classified",
    }
    write_log(entry)

    return jsonify({
        "content_id": content_id,
        "attribution": attribution,
        "confidence": llm_score,
        "label": "TBD in M5",
    })


@app.route("/log", methods=["GET"])
def log():
    n = request.args.get("n", 20, type=int)
    return jsonify({"entries": get_log(n)})


# ---------------------------------------------------------------------------
# Init + run
# ---------------------------------------------------------------------------

if __name__ == "__main__":
    init_db()
    app.run(debug=True)
