import uuid
import json
import datetime
import os
import sqlite3
import math
import re

from flask import Flask, request, jsonify
from flask_limiter import Limiter
from flask_limiter.util import get_remote_address
from dotenv import load_dotenv
from groq import Groq

load_dotenv()

app = Flask(__name__)
client = Groq(api_key=os.environ.get("GROQ_API_KEY"))

limiter = Limiter(
    get_remote_address,
    app=app,
    default_limits=[],
    storage_uri="memory://",
)


# ---------------------------------------------------------------------------
# Database
# ---------------------------------------------------------------------------

def init_db():
    conn = sqlite3.connect("audit.db")
    conn.execute("""
        CREATE TABLE IF NOT EXISTS log (
            content_id        TEXT,
            creator_id        TEXT,
            timestamp         TEXT,
            attribution       TEXT,
            confidence        REAL,
            llm_score         REAL,
            stylometric_score REAL,
            status            TEXT,
            entry_type        TEXT DEFAULT 'classification',
            appeal_reasoning  TEXT
        )
    """)
    conn.commit()
    conn.close()


def write_log(entry: dict):
    conn = sqlite3.connect("audit.db")
    conn.execute(
        "INSERT INTO log VALUES (?,?,?,?,?,?,?,?,?,?)",
        (
            entry["content_id"],
            entry["creator_id"],
            entry["timestamp"],
            entry.get("attribution", ""),
            entry.get("confidence", 0.0),
            entry.get("llm_score", 0.0),
            entry.get("stylometric_score", 0.0),
            entry["status"],
            entry.get("entry_type", "classification"),
            entry.get("appeal_reasoning", None),
        ),
    )
    conn.commit()
    conn.close()


def get_log(n: int = 20) -> list[dict]:
    conn = sqlite3.connect("audit.db")
    rows = conn.execute(
        "SELECT * FROM log ORDER BY timestamp DESC LIMIT ?", (n,)
    ).fetchall()
    conn.close()
    cols = ["content_id", "creator_id", "timestamp", "attribution",
            "confidence", "llm_score", "stylometric_score", "status",
            "entry_type", "appeal_reasoning"]
    return [dict(zip(cols, row)) for row in rows]


def get_entry(content_id: str) -> dict | None:
    conn = sqlite3.connect("audit.db")
    row = conn.execute(
        "SELECT * FROM log WHERE content_id = ? AND entry_type = 'classification'",
        (content_id,)
    ).fetchone()
    conn.close()
    if not row:
        return None
    cols = ["content_id", "creator_id", "timestamp", "attribution",
            "confidence", "llm_score", "stylometric_score", "status",
            "entry_type", "appeal_reasoning"]
    return dict(zip(cols, row))


def update_status(content_id: str, status: str):
    conn = sqlite3.connect("audit.db")
    conn.execute(
        "UPDATE log SET status = ? WHERE content_id = ?",
        (status, content_id)
    )
    conn.commit()
    conn.close()


# ---------------------------------------------------------------------------
# Signal 1: LLM classification
# ---------------------------------------------------------------------------

def llm_classify(text: str) -> float:
    prompt = (
        "Analyze the following text and assess whether it was written by a human "
        "or generated by an AI writing tool.\n\n"
        "Return ONLY a JSON object in this exact format, with no other text:\n"
        '{"ai_score": 0.0}\n\n'
        "Where ai_score is a float between 0.0 (confident the text is human-written) "
        "and 1.0 (confident the text is AI-generated).\n\n"
        f"Text to analyze:\n{text}"
    )

    response = client.chat.completions.create(
        model="llama-3.3-70b-versatile",
        messages=[{"role": "user", "content": prompt}],
        temperature=0.1,
    )

    raw = response.choices[0].message.content.strip()

    try:
        result = json.loads(raw)
        return float(result["ai_score"])
    except (json.JSONDecodeError, KeyError, ValueError) as e:
        print(f"[llm_classify] Failed to parse response: {e!r}")
        print(f"[llm_classify] Raw output was: {raw!r}")
        return 0.5


# ---------------------------------------------------------------------------
# Signal 2: Stylometric heuristics
# ---------------------------------------------------------------------------

def stylometric_score(text: str) -> float:
    sentences = [s.strip() for s in re.split(r'[.!?]+', text) if s.strip()]
    if not sentences:
        return 0.5

    word_counts = [len(s.split()) for s in sentences]
    words = text.split()
    total_words = len(words)

    # 1. Sentence length variance (AI = uniform = low std_dev = high score)
    if len(word_counts) > 1:
        mean_wc = sum(word_counts) / len(word_counts)
        variance = sum((wc - mean_wc) ** 2 for wc in word_counts) / len(word_counts)
        std_dev = math.sqrt(variance)
    else:
        std_dev = 0.0

    slv_score = max(0.0, 1.0 - (std_dev / 6.0))

    # 2. Punctuation density (AI = conservative = low punct = high score)
    if total_words > 0:
        punct_chars = len(re.findall(r'[,;:\-—–…!?]', text))
        punct_per_100 = (punct_chars / total_words) * 100
    else:
        punct_per_100 = 0.0

    punct_score = max(0.0, 1.0 - (punct_per_100 / 8.0))

    # 3. Average sentence length (AI = longer, more complete sentences)
    mean_wc = sum(word_counts) / len(word_counts) if word_counts else 10
    avg_len_score = min(1.0, max(0.0, (mean_wc - 8) / 12.0))

    combined = (0.5 * slv_score) + (0.3 * punct_score) + (0.2 * avg_len_score)
    return round(min(1.0, max(0.0, combined)), 4)


# ---------------------------------------------------------------------------
# Confidence scoring
# ---------------------------------------------------------------------------

def combine_scores(llm_score: float, stylo_score: float, word_count: int) -> float:
    raw = (0.7 * llm_score) + (0.3 * stylo_score)
    clamped = min(1.0, max(0.0, raw))
    if word_count < 50:
        clamped = min(clamped, 0.70)
    return round(clamped, 4)


# ---------------------------------------------------------------------------
# Transparency label
# ---------------------------------------------------------------------------

def generate_label(confidence: float) -> dict:
    pct = round(confidence * 100)

    if confidence >= 0.65:
        return {
            "label_variant": "likely_ai",
            "label_text": (
                f"⚠️ Likely AI-Generated\n"
                f"Our system found strong signals that this content was produced by an AI writing tool.\n"
                f"Confidence: {pct}%\n"
                f"If this is wrong, the creator can submit an appeal below."
            ),
        }
    elif confidence >= 0.36:
        return {
            "label_variant": "uncertain",
            "label_text": (
                f"🔍 Origin Unclear\n"
                f"Our system couldn't determine with confidence whether this content was written by a human or generated by AI.\n"
                f"Confidence: {pct}%\n"
                f"If you're the creator, you can submit an appeal to provide more context."
            ),
        }
    else:
        return {
            "label_variant": "likely_human",
            "label_text": (
                f"✅ Likely Human-Written\n"
                f"Our system found no strong signals of AI generation in this content.\n"
                f"Confidence: {pct}% human"
            ),
        }


# ---------------------------------------------------------------------------
# Routes
# ---------------------------------------------------------------------------

@app.route("/submit", methods=["POST"])
@limiter.limit("10 per minute;100 per day")
def submit():
    data = request.get_json(force=True, silent=True)
    if not data:
        return jsonify({"error": "Invalid or missing JSON body"}), 400

    text = data.get("text", "").strip()
    creator_id = data.get("creator_id", "").strip()

    if not text:
        return jsonify({"error": "Missing required field: text"}), 400
    if not creator_id:
        return jsonify({"error": "Missing required field: creator_id"}), 400

    content_id = str(uuid.uuid4())
    word_count = len(text.split())

    llm = llm_classify(text)
    stylo = stylometric_score(text)
    confidence = combine_scores(llm, stylo, word_count)

    if confidence >= 0.65:
        attribution = "likely_ai"
    elif confidence >= 0.36:
        attribution = "uncertain"
    else:
        attribution = "likely_human"

    label = generate_label(confidence)

    entry = {
        "content_id": content_id,
        "creator_id": creator_id,
        "timestamp": datetime.datetime.utcnow().isoformat() + "Z",
        "attribution": attribution,
        "confidence": confidence,
        "llm_score": llm,
        "stylometric_score": stylo,
        "status": "classified",
        "entry_type": "classification",
        "appeal_reasoning": None,
    }
    write_log(entry)

    return jsonify({
        "content_id": content_id,
        "attribution": attribution,
        "confidence": confidence,
        "llm_score": llm,
        "stylometric_score": stylo,
        "label_variant": label["label_variant"],
        "label_text": label["label_text"],
    })


@app.route("/appeal", methods=["POST"])
def appeal():
    data = request.get_json(force=True, silent=True)
    if not data:
        return jsonify({"error": "Invalid or missing JSON body"}), 400

    content_id = data.get("content_id", "").strip()
    creator_id = data.get("creator_id", "").strip()
    reasoning = data.get("creator_reasoning", "").strip()

    if not content_id:
        return jsonify({"error": "Missing required field: content_id"}), 400
    if not creator_id:
        return jsonify({"error": "Missing required field: creator_id"}), 400
    if not reasoning or len(reasoning) < 20:
        return jsonify({"error": "creator_reasoning must be at least 20 characters"}), 400

    original = get_entry(content_id)
    if not original:
        return jsonify({"error": "content_id not found"}), 404

    if original["creator_id"] != creator_id:
        return jsonify({"error": "creator_id does not match original submission"}), 403

    if original["status"] == "under_review":
        return jsonify({"error": "An appeal is already under review for this content"}), 409

    update_status(content_id, "under_review")

    appeal_entry = {
        "content_id": content_id,
        "creator_id": creator_id,
        "timestamp": datetime.datetime.utcnow().isoformat() + "Z",
        "attribution": original["attribution"],
        "confidence": original["confidence"],
        "llm_score": original["llm_score"],
        "stylometric_score": original["stylometric_score"],
        "status": "under_review",
        "entry_type": "appeal",
        "appeal_reasoning": reasoning,
    }
    write_log(appeal_entry)

    return jsonify({
        "content_id": content_id,
        "status": "under_review",
        "message": "Your appeal has been received and will be reviewed. No automated re-classification will occur.",
    })


@app.route("/log", methods=["GET"])
def log():
    n = request.args.get("n", 20, type=int)
    return jsonify({"entries": get_log(n)})


@app.route("/appeals", methods=["GET"])
def appeals_queue():
    conn = sqlite3.connect("audit.db")
    rows = conn.execute(
        "SELECT * FROM log WHERE entry_type = 'appeal' ORDER BY timestamp DESC"
    ).fetchall()
    conn.close()
    cols = ["content_id", "creator_id", "timestamp", "attribution",
            "confidence", "llm_score", "stylometric_score", "status",
            "entry_type", "appeal_reasoning"]
    return jsonify({"appeals": [dict(zip(cols, row)) for row in rows]})


# ---------------------------------------------------------------------------
# Init + run
# ---------------------------------------------------------------------------

if __name__ == "__main__":
    init_db()
    app.run(debug=True)